apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-pv
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /run/desktop/mnt/host/c/personal/learning/airflow/dags
    type: Directory