apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs-pv
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 3Gi
  hostPath:
    path: /run/desktop/mnt/host/c/personal/learning/airflow/logs
    type: Directory